/**
 * LUMIERE STUDIO - TEMPLATES PRESETS & CATALOG DATA
 */

const TEMPLATE_PRESETS = [
    {
        id: 'cyber_samurai',
        name: 'Cyber Samurai 2099',
        category: 'vip',
        tag: 'NEW Cyberpunk',
        desc: 'Thành phố tương lai rực rỡ ánh đèn Neon cùng kiếm sĩ Cyberpunk siêu nét 8K',
        bgType: 'image',
        imageSrc: 'image/cyber_samurai_city.jpg',
        posterImg: 'image/cyber_samurai_city.jpg',
        title: 'CYBER SAMURAI',
        subtitle: 'NEON PROTOCOL // NIGHT CITY',
        badge: 'CYBERPUNK 8K',
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 4.5,
        letterSpacing: 6,
        colorStart: '#00f0ff',
        colorEnd: '#ff007f',
        glowColor: '#00f0ff',
        glowBlur: 30,
        textPosY: 75,
        textPosX: 50,
        frameStyle: 'frame-cyber-hud',
        frameColor: '#00f0ff',
        frameWidth: 2,
        particleType: 'cyber_sparks',
        particleCount: 85,
        particleSpeed: 1.5,
        particleColor: '#00f0ff',
        particleColor2: '#ff007f',
        brightness: 1.05,
        contrast: 1.1,
        vignette: 0.6,
        audioSrc: ''
    },
    {
        id: 'dragon_shrine',
        name: 'Celestial Dragon Shrine',
        category: 'anime',
        tag: 'NEW Fantasy',
        desc: 'Rồng thần hoàng kim uy nghiêm bay lượn trên biển mây cổng Torii lung linh',
        bgType: 'image',
        imageSrc: 'image/mystic_dragon_shrine.jpg',
        posterImg: 'image/mystic_dragon_shrine.jpg',
        title: 'Thần Long Hoàng Kim',
        subtitle: 'CELESTIAL DRAGON SPIRIT SHRINE',
        badge: 'MYTHIC 8K',
        fontFamily: "'Cinzel Decorative', serif",
        fontSize: 4.2,
        letterSpacing: 4,
        colorStart: '#fffbe6',
        colorEnd: '#f59e0b',
        glowColor: '#f59e0b',
        glowBlur: 28,
        textPosY: 78,
        textPosX: 50,
        frameStyle: 'frame-luxury-gold',
        frameColor: '#ffd700',
        frameWidth: 2,
        particleType: 'gold_dust',
        particleCount: 100,
        particleSpeed: 1.2,
        particleColor: '#fbbf24',
        particleColor2: '#f472b6',
        brightness: 1.05,
        contrast: 1.05,
        vignette: 0.5,
        audioSrc: ''
    },
    {
        id: 'cosmic_nebula',
        name: 'Cosmic Infinity Nebula',
        category: 'vip',
        tag: 'NEW Cosmic',
        desc: 'Vành đai tinh vân vũ trụ đa sắc màu huyền bí cùng những đám mây bụi sao vô tận',
        bgType: 'image',
        imageSrc: 'image/cosmic_galaxy_nebula.jpg',
        posterImg: 'image/cosmic_galaxy_nebula.jpg',
        title: 'Infinity Cosmos',
        subtitle: 'DEEP SPACE NEBULA HORIZON',
        badge: 'GALAXY 8K',
        fontFamily: "'Outfit', sans-serif",
        fontSize: 4.8,
        letterSpacing: 8,
        colorStart: '#ffffff',
        colorEnd: '#c084fc',
        glowColor: '#a855f7',
        glowBlur: 25,
        textPosY: 50,
        textPosX: 50,
        frameStyle: 'frame-holographic',
        frameColor: '#a855f7',
        frameWidth: 2,
        particleType: 'constellation',
        particleCount: 95,
        particleSpeed: 1.1,
        particleColor: '#c084fc',
        particleColor2: '#60a5fa',
        brightness: 1.0,
        contrast: 1.1,
        vignette: 0.6,
        audioSrc: ''
    },
    {
        id: 'vip1',
        name: 'VIP 1: Platinum Starfield',
        category: 'vip',
        tag: 'VIP Video',
        desc: 'Hiệu ứng ánh sao bạch kim thần thánh tương tác chuột với video nền siêu mượt',
        bgType: 'video',
        videoSrc: 'video/holy.mp4',
        posterImg: 'image/v (1).jpg',
        title: 'Lumière Divine',
        subtitle: 'PREMIUM INTERACTIVE WALLPAPER',
        badge: 'VIP EDITION',
        fontFamily: "'Great Vibes', cursive",
        fontSize: 5.5,
        letterSpacing: 2,
        colorStart: '#ffffff',
        colorEnd: '#a5c9ff',
        glowColor: '#64b4ff',
        glowBlur: 25,
        textPosY: 75,
        textPosX: 50,
        frameStyle: 'frame-none',
        frameColor: '#00f0ff',
        particleType: 'sparkles',
        particleCount: 75,
        particleSpeed: 1,
        particleColor: '#ffffff',
        particleColor2: '#a5c9ff',
        brightness: 1.1,
        contrast: 1.05,
        vignette: 0.6,
        audioSrc: ''
    },
    {
        id: 'vip2',
        name: 'VIP 2: Celestial Constellations',
        category: 'vip',
        tag: 'VIP Video',
        desc: 'Mạng lưới chòm sao lấp lánh liên kết tia sáng theo vị trí con trỏ chuột',
        bgType: 'video',
        videoSrc: 'video/nen4k.mp4',
        posterImg: 'image/v (2).jpg',
        title: 'Celestial Dream',
        subtitle: 'CONSTELLATION NETWORK FX',
        badge: 'VIP EDITION',
        fontFamily: "'Cinzel Decorative', serif",
        fontSize: 4.2,
        letterSpacing: 6,
        colorStart: '#ffffff',
        colorEnd: '#ffd700',
        glowColor: '#ffd700',
        glowBlur: 20,
        textPosY: 50,
        textPosX: 50,
        frameStyle: 'frame-luxury-gold',
        frameColor: '#ffd700',
        particleType: 'constellation',
        particleCount: 85,
        particleSpeed: 1.2,
        particleColor: '#ffd700',
        particleColor2: '#ff9800',
        brightness: 1.0,
        contrast: 1.1,
        vignette: 0.7,
        audioSrc: ''
    },
    {
        id: 'vip3',
        name: 'VIP 3: Golden Ember Trail',
        category: 'vip',
        tag: 'VIP Video',
        desc: 'Bụi vàng ma thuật chuyển động cuộn xoáy phát sáng theo chuyển động chuột',
        bgType: 'video',
        videoSrc: 'video/vip.mp4',
        posterImg: 'image/v (3).jpg',
        title: 'Golden Sovereignty',
        subtitle: 'MYSTIC GOLDEN EMBERS',
        badge: 'VIP EDITION',
        fontFamily: "'Great Vibes', cursive",
        fontSize: 5.2,
        letterSpacing: 3,
        colorStart: '#fffbe6',
        colorEnd: '#f59e0b',
        glowColor: '#f59e0b',
        glowBlur: 30,
        textPosY: 50,
        textPosX: 50,
        frameStyle: 'frame-none',
        frameColor: '#f59e0b',
        particleType: 'gold_dust',
        particleCount: 110,
        particleSpeed: 1.4,
        particleColor: '#fbbf24',
        particleColor2: '#ef4444',
        brightness: 1.1,
        contrast: 1.1,
        vignette: 0.6,
        audioSrc: ''
    },
    {
        id: 'vip4',
        name: 'VIP 4: Cyber Neon Pulse',
        category: 'vip',
        tag: 'VIP Video',
        desc: 'Phong cách Cyberpunk tương lai với tia sáng neon và khung HUD công nghệ cao',
        bgType: 'video',
        videoSrc: 'video/blackgoku.mp4',
        posterImg: 'image/v (4).jpg',
        title: 'CYBERPUNK 2099',
        subtitle: 'HIGH TECH OVERLAY PROTOCOL',
        badge: 'CYBER HUD',
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 4.0,
        letterSpacing: 8,
        colorStart: '#00f0ff',
        colorEnd: '#ff007f',
        glowColor: '#00f0ff',
        glowBlur: 30,
        textPosY: 50,
        textPosX: 50,
        frameStyle: 'frame-cyber-hud',
        frameColor: '#00f0ff',
        particleType: 'cyber_sparks',
        particleCount: 90,
        particleSpeed: 1.8,
        particleColor: '#00f0ff',
        particleColor2: '#ff007f',
        brightness: 1.1,
        contrast: 1.2,
        vignette: 0.8,
        audioSrc: ''
    },
    {
        id: 'vip5',
        name: 'VIP 5: 3D Coverflow Showcase',
        category: 'gallery',
        tag: '3D Slider',
        desc: 'Bộ sưu tập thẻ ảnh 3D chiều sâu perspective chuyển cảnh mượt mà vô hạn',
        bgType: 'slider_3d',
        videoSrc: '',
        posterImg: 'image/v (1).png',
        slides: [
            'image/v (1).png',
            'image/v (2).png',
            'image/v (3).png',
            'image/v (4).png',
            'image/v (5).png',
            'image/v (6).png',
            'image/v (7).png',
            'image/v (8).png'
        ],
        title: '3D Horizon Cards',
        subtitle: 'PERSPECTIVE CAROUSEL ENGINE',
        badge: '3D GALLERY',
        fontFamily: "'Montserrat', sans-serif",
        fontSize: 3.2,
        letterSpacing: 6,
        colorStart: '#ffffff',
        colorEnd: '#a5c9ff',
        glowColor: '#5887ff',
        glowBlur: 20,
        textPosY: 22,
        textPosX: 50,
        frameStyle: 'frame-none',
        particleType: 'sparkles',
        particleCount: 50,
        particleSpeed: 0.8,
        particleColor: '#a5c9ff',
        particleColor2: '#ffffff',
        brightness: 1.0,
        contrast: 1.0,
        vignette: 0.5,
        audioSrc: ''
    },
    {
        id: 'vip6',
        name: 'VIP 6: Infinite Focus Depth',
        category: 'gallery',
        tag: '3D Slider',
        desc: 'Slider 3D chiều dọc xoay vòng tập trung trung tâm tạo cảm giác sang trọng',
        bgType: 'slider_3d',
        videoSrc: '',
        posterImg: 'image/v (5).png',
        slides: [
            'image/v (5).png',
            'image/v (6).png',
            'image/v (7).png',
            'image/v (8).png',
            'image/v (1).png',
            'image/v (2).png'
        ],
        title: 'Infinite Focus',
        subtitle: 'IMMERSIVE SHOWCASE SLIDER',
        badge: 'VIP GALLERY',
        fontFamily: "'Outfit', sans-serif",
        fontSize: 3.5,
        letterSpacing: 4,
        colorStart: '#ffffff',
        colorEnd: '#ff7bcf',
        glowColor: '#ff7bcf',
        glowBlur: 20,
        textPosY: 20,
        textPosX: 50,
        frameStyle: 'frame-none',
        particleType: 'bokeh',
        particleCount: 40,
        particleSpeed: 0.6,
        particleColor: '#ff7bcf',
        particleColor2: '#a5c9ff',
        brightness: 1.0,
        contrast: 1.0,
        vignette: 0.6,
        audioSrc: ''
    },
    {
        id: 'v1',
        name: 'V1: Magic Dust Red & Gold',
        category: 'vfx',
        tag: 'Magic VFX',
        desc: 'Dòng chảy bụi sao đỏ vàng rực rỡ bay lượn với chuyển động ngẫu nhiên tuyệt đẹp',
        bgType: 'video',
        videoSrc: 'video/pro.mp4',
        posterImg: 'image/v (1).jpg',
        title: 'Crimson Flame',
        subtitle: 'MAGIC DUST RED & GOLD',
        badge: 'ORIGINAL V1',
        fontFamily: "'Great Vibes', cursive",
        fontSize: 5.0,
        letterSpacing: 2,
        colorStart: '#ffffff',
        colorEnd: '#ff2600',
        glowColor: '#ff4d4d',
        glowBlur: 20,
        textPosY: 50,
        textPosX: 50,
        frameStyle: 'frame-none',
        particleType: 'gold_dust',
        particleCount: 120,
        particleSpeed: 1.5,
        particleColor: '#ffd700',
        particleColor2: '#ff3300',
        brightness: 1.1,
        contrast: 1.0,
        vignette: 0.5,
        audioSrc: ''
    },
    {
        id: 'v2',
        name: 'V2: Starlight Nebula',
        category: 'vfx',
        tag: 'Magic VFX',
        desc: 'Tinh vân vũ trụ kết nối sao động phản hồi theo cử chỉ tay và chuột',
        bgType: 'video',
        videoSrc: 'video/zenitsu.mp4',
        posterImg: 'image/v (2).jpg',
        title: 'Thunder Starlight',
        subtitle: 'NEBULA CONSTELLATION MESH',
        badge: 'ORIGINAL V2',
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 4.2,
        letterSpacing: 6,
        colorStart: '#ffffff',
        colorEnd: '#ffe600',
        glowColor: '#ffe600',
        glowBlur: 25,
        textPosY: 50,
        textPosX: 50,
        frameStyle: 'frame-cyber-hud',
        frameColor: '#ffe600',
        particleType: 'constellation',
        particleCount: 95,
        particleSpeed: 1.6,
        particleColor: '#ffe600',
        particleColor2: '#ff9000',
        brightness: 1.1,
        contrast: 1.1,
        vignette: 0.6,
        audioSrc: ''
    },
    {
        id: 'v3',
        name: 'V3: Forest Fireflies & Bokeh',
        category: 'vfx',
        tag: 'Magic VFX',
        desc: 'Đom đóm phát sáng nhấp nháy êm dịu trôi bồng bềnh trong màn đêm',
        bgType: 'video',
        videoSrc: 'video/itachi.mp4',
        posterImg: 'image/v (3).jpg',
        title: 'Shadow & Glow',
        subtitle: 'FIREFLY BOKEH ATMOSPHERE',
        badge: 'ORIGINAL V3',
        fontFamily: "'Dancing Script', cursive",
        fontSize: 4.8,
        letterSpacing: 2,
        colorStart: '#ffffff',
        colorEnd: '#a7f3d0',
        glowColor: '#10b981',
        glowBlur: 25,
        textPosY: 50,
        textPosX: 50,
        frameStyle: 'frame-glass-luxe',
        particleType: 'bokeh',
        particleCount: 50,
        particleSpeed: 0.7,
        particleColor: '#6ee7b7',
        particleColor2: '#fef08a',
        brightness: 1.0,
        contrast: 1.0,
        vignette: 0.6,
        audioSrc: ''
    },
    {
        id: 'v4',
        name: 'V4: Energy Cyber Vortex',
        category: 'vfx',
        tag: 'Magic VFX',
        desc: 'Vòng xoáy năng lượng tốc độ cao tương tác xung lực cực mạnh',
        bgType: 'video',
        videoSrc: 'video/ultragoku.mp4',
        posterImg: 'image/v (4).jpg',
        title: 'Ultra Instinct',
        subtitle: 'ENERGY VORTEX SYSTEM',
        badge: 'ORIGINAL V4',
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 4.5,
        letterSpacing: 8,
        colorStart: '#ffffff',
        colorEnd: '#c084fc',
        glowColor: '#a855f7',
        glowBlur: 30,
        textPosY: 50,
        textPosX: 50,
        frameStyle: 'frame-holographic',
        particleType: 'cyber_sparks',
        particleCount: 130,
        particleSpeed: 2.2,
        particleColor: '#c084fc',
        particleColor2: '#60a5fa',
        brightness: 1.15,
        contrast: 1.15,
        vignette: 0.7,
        audioSrc: ''
    },
    {
        id: 'menmaume',
        name: 'Menma Ume: Sakura Breeze',
        category: 'anime',
        tag: 'Anime FX',
        desc: 'Cánh hoa anh đào rơi bồng bềnh lãng mạn kết hợp cùng ánh sáng lung linh',
        bgType: 'video',
        videoSrc: 'video/ayanami.mp4',
        posterImg: 'image/v (6).jpg',
        title: 'Sakura Memories',
        subtitle: 'ETERNAL BLOSSOM DANCE',
        badge: 'ANIME SPECIAL',
        fontFamily: "'Great Vibes', cursive",
        fontSize: 5.2,
        letterSpacing: 2,
        colorStart: '#ffffff',
        colorEnd: '#f472b6',
        glowColor: '#f472b6',
        glowBlur: 25,
        textPosY: 70,
        textPosX: 50,
        frameStyle: 'frame-anime-glow',
        frameColor: '#f472b6',
        particleType: 'sakura',
        particleCount: 65,
        particleSpeed: 1.1,
        particleColor: '#fbcfe8',
        particleColor2: '#f472b6',
        brightness: 1.05,
        contrast: 1.05,
        vignette: 0.5,
        audioSrc: ''
    },
    {
        id: 'meov2',
        name: 'Meo V2: Cyber Anime Neon',
        category: 'anime',
        tag: 'Anime FX',
        desc: 'Giao diện phong cách Anime Meo Neon rực rỡ kết hợp hiệu ứng tia sao thần thái',
        bgType: 'video',
        videoSrc: 'video/albedos.mp4',
        posterImg: 'image/v (7).jpg',
        title: 'Pure White Maiden',
        subtitle: 'CYBER ANIME INTERACTIVE',
        badge: 'ANIME V2',
        fontFamily: "'Cinzel Decorative', serif",
        fontSize: 4.2,
        letterSpacing: 4,
        colorStart: '#ffffff',
        colorEnd: '#a5f3fc',
        glowColor: '#38bdf8',
        glowBlur: 25,
        textPosY: 75,
        textPosX: 50,
        frameStyle: 'frame-glass-luxe',
        particleType: 'sparkles',
        particleCount: 80,
        particleSpeed: 1.2,
        particleColor: '#bae6fd',
        particleColor2: '#ffffff',
        brightness: 1.1,
        contrast: 1.1,
        vignette: 0.6,
        audioSrc: ''
    },
    {
        id: 'parallax',
        name: 'Parallax: Mystic Forest',
        category: 'parallax',
        tag: '3D Parallax',
        desc: 'Không gian rừng bí ẩn 3 lớp (Hậu cảnh, Trung cảnh, Tiền cảnh) xoay chuyển đa chiều',
        bgType: 'parallax',
        videoSrc: '',
        posterImg: 'image/v (8).jpg',
        parallaxLayers: [
            { img: 'https://images.unsplash.com/photo-1508624217470-5ef0f947d8be?q=80&w=2070&auto=format&fit=crop', speed: 0.02 },
            { img: 'https://png.pngtree.com/png-clipart/20230913/ourmid/pngtree-foggy-mountain-forest-landscape-png-image_10096122.png', speed: 0.06 },
            { img: '', speed: 0.12 }
        ],
        title: 'Mystic Sanctuary',
        subtitle: '3D MULTI-LAYER PARALLAX DEPTH',
        badge: 'PARALLAX 3D',
        fontFamily: "'Cinzel Decorative', serif",
        fontSize: 4.4,
        letterSpacing: 6,
        colorStart: '#ffffff',
        colorEnd: '#93c5fd',
        glowColor: '#60a5fa',
        glowBlur: 25,
        textPosY: 50,
        textPosX: 50,
        frameStyle: 'frame-none',
        particleType: 'bokeh',
        particleCount: 45,
        particleSpeed: 0.6,
        particleColor: '#93c5fd',
        particleColor2: '#ffffff',
        brightness: 0.9,
        contrast: 1.1,
        vignette: 0.7,
        audioSrc: ''
    },
    {
        id: 'demo1',
        name: 'Gallery Showcase Modern',
        category: 'gallery',
        tag: 'Gallery',
        desc: 'Showcase ảnh độ phân giải cao kết hợp background blur mịn màng',
        bgType: 'slider_3d',
        videoSrc: '',
        posterImg: 'image/v (1) bg.png',
        slides: [
            'image/v (1) bg.png',
            'image/v (2) bg.png',
            'image/v (3) bg.png',
            'image/v (4) bg.png'
        ],
        title: 'Lumière Showcase',
        subtitle: 'HIGH PERFORMANCE VISUALS',
        badge: 'GALLERY',
        fontFamily: "'Montserrat', sans-serif",
        fontSize: 3.8,
        letterSpacing: 6,
        colorStart: '#ffffff',
        colorEnd: '#a5c9ff',
        glowColor: '#5887ff',
        glowBlur: 20,
        textPosY: 25,
        textPosX: 50,
        frameStyle: 'frame-none',
        particleType: 'sparkles',
        particleCount: 40,
        particleSpeed: 0.8,
        particleColor: '#a5c9ff',
        particleColor2: '#ffffff',
        brightness: 1.0,
        contrast: 1.0,
        vignette: 0.6,
        audioSrc: ''
    }
];

// Available local video list for selection
const LOCAL_VIDEOS = [
    { name: 'Holy Light Stream', src: 'video/holy.mp4' },
    { name: 'Nền 4K Thần Thánh', src: 'video/nen4k.mp4' },
    { name: 'VIP Gold Particles', src: 'video/vip.mp4' },
    { name: 'VIP 2 Celestial Flow', src: 'video/vip2.mp4' },
    { name: 'Black Goku Super Saiyan', src: 'video/blackgoku.mp4' },
    { name: 'Zenitsu Lightning', src: 'video/zenitsu.mp4' },
    { name: 'Itachi Uchiha Moonlight', src: 'video/itachi.mp4' },
    { name: 'Ayanami Rei Floating', src: 'video/ayanami.mp4' },
    { name: 'Albedo Overlord', src: 'video/albedos.mp4' },
    { name: 'Ultra Instinct Goku', src: 'video/ultragoku.mp4' },
    { name: 'Luffy Gear 5 Sun God', src: 'video/lufy1.mp4' },
    { name: 'Konan Paper Dance', src: 'video/konan.mp4' },
    { name: 'Rose Goku Black', src: 'video/rose.mp4' },
    { name: 'Pro Magic Energy', src: 'video/pro.mp4' },
    { name: 'Pro 2 Cosmic Drive', src: 'video/pro2.mp4' },
    { name: 'Linhbell Ambient Night', src: 'video/linhbell.mp4' },
    { name: 'Deep Cosmic V22', src: 'video/v22.mp4' }
];

// Available local images list for selection
const LOCAL_IMAGES = [
    { name: 'Cyber Samurai 8K', src: 'image/cyber_samurai_city.jpg', thumb: 'image/cyber_samurai_city.jpg' },
    { name: 'Dragon Shrine 8K', src: 'image/mystic_dragon_shrine.jpg', thumb: 'image/mystic_dragon_shrine.jpg' },
    { name: 'Cosmic Nebula 8K', src: 'image/cosmic_galaxy_nebula.jpg', thumb: 'image/cosmic_galaxy_nebula.jpg' },
    { name: 'Character 1 Portrait', src: 'image/v (1).png', thumb: 'image/v (1).jpg' },
    { name: 'Character 2 Portrait', src: 'image/v (2).png', thumb: 'image/v (2).jpg' },
    { name: 'Character 3 Portrait', src: 'image/v (3).png', thumb: 'image/v (3).jpg' },
    { name: 'Character 4 Portrait', src: 'image/v (4).png', thumb: 'image/v (4).jpg' },
    { name: 'Character 5 Portrait', src: 'image/v (5).png', thumb: 'image/v (5).jpg' },
    { name: 'Character 6 Portrait', src: 'image/v (6).png', thumb: 'image/v (6).jpg' },
    { name: 'Character 7 Portrait', src: 'image/v (7).png', thumb: 'image/v (7).jpg' },
    { name: 'Character 8 Portrait', src: 'image/v (8).png', thumb: 'image/v (8).jpg' },
    { name: 'Background 1 Landscape', src: 'image/v (1) bg.png', thumb: 'image/v (1) bg.png' },
    { name: 'Background 2 Landscape', src: 'image/v (2) bg.png', thumb: 'image/v (2) bg.png' },
    { name: 'Background 3 Landscape', src: 'image/v (3) bg.png', thumb: 'image/v (3) bg.png' },
    { name: 'Background 4 Landscape', src: 'image/v (4) bg.png', thumb: 'image/v (4) bg.png' }
];
